<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>R Notebook</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>




<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 51px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h2 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h3 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h4 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h5 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h6 {
  padding-top: 56px;
  margin-top: -56px;
}
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #ffffff;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Disease Predictions</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="Parkinsons-notebook.html">Parkinsons Disease Prediction</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">R Notebook</h1>

</div>


<p>Parkinson’s disease (PD) is a neurodegenerative disorder that affects predominately dopamine-producing neurons in a specific area of the brain called substantia nigra.</p>
<p>Symptoms generally develop slowly over years. The progression of symptoms is often a bit different from one person to another due to the diversity of the disease. People with PD may experience:</p>
<p>Tremor, mainly at rest and described as pill rolling tremor in hands. Other forms of tremor are possible Slowness of movements (bradykinesia) Limb rigidity Gait and balance problems Let’s come to the dataset. This dataset is from UCI Machine Learning Repository.This dataset is composed of a range of biomedical voice measurements from 31 people, 23 with Parkinson’s disease (PD). Each column in the table is a particular voice measure, and each row corresponds one of 195 voice recording from these individuals (“name” column). The main aim of the data is to discriminate healthy people from those with PD, according to “status” column which is set to 0 for healthy and 1 for PD.</p>
<p>Our problem is to predict any individual as healthy or not. Parkinson’s disease (PD) is a neurodegenerative disorder that affects predominately dopamine-producing neurons in a specific area of the brain called substantia nigra.</p>
<p>Symptoms generally develop slowly over years. The progression of symptoms is often a bit different from one person to another due to the diversity of the disease. People with PD may experience:</p>
<p>Tremor, mainly at rest and described as pill rolling tremor in hands. Other forms of tremor are possible Slowness of movements (bradykinesia) Limb rigidity Gait and balance problems Let’s come to the dataset. This dataset is from UCI Machine Learning Repository.This dataset is composed of a range of biomedical voice measurements from 31 people, 23 with Parkinson’s disease (PD). Each column in the table is a particular voice measure, and each row corresponds one of 195 voice recording from these individuals (“name” column). The main aim of the data is to discriminate healthy people from those with PD, according to “status” column which is set to 0 for healthy and 1 for PD. We will be using Logistic Regression.</p>
<p>Our problem is to predict any individual as healthy or not.</p>
<pre class="r"><code>data &lt;- read.csv(file = &#39;parkinsons.data&#39;)</code></pre>
<p>We have our data set called “data”. Let’s get a view and summary of the dataset.</p>
<pre class="r"><code>head(data,6)</code></pre>
<pre><code>##             name MDVP.Fo.Hz. MDVP.Fhi.Hz. MDVP.Flo.Hz. MDVP.Jitter...
## 1 phon_R01_S01_1     119.992      157.302       74.997        0.00784
## 2 phon_R01_S01_2     122.400      148.650      113.819        0.00968
## 3 phon_R01_S01_3     116.682      131.111      111.555        0.01050
## 4 phon_R01_S01_4     116.676      137.871      111.366        0.00997
## 5 phon_R01_S01_5     116.014      141.781      110.655        0.01284
## 6 phon_R01_S01_6     120.552      131.162      113.787        0.00968
##   MDVP.Jitter.Abs. MDVP.RAP MDVP.PPQ Jitter.DDP MDVP.Shimmer MDVP.Shimmer.dB.
## 1          0.00007  0.00370  0.00554    0.01109      0.04374            0.426
## 2          0.00008  0.00465  0.00696    0.01394      0.06134            0.626
## 3          0.00009  0.00544  0.00781    0.01633      0.05233            0.482
## 4          0.00009  0.00502  0.00698    0.01505      0.05492            0.517
## 5          0.00011  0.00655  0.00908    0.01966      0.06425            0.584
## 6          0.00008  0.00463  0.00750    0.01388      0.04701            0.456
##   Shimmer.APQ3 Shimmer.APQ5 MDVP.APQ Shimmer.DDA     NHR    HNR status     RPDE
## 1      0.02182      0.03130  0.02971     0.06545 0.02211 21.033      1 0.414783
## 2      0.03134      0.04518  0.04368     0.09403 0.01929 19.085      1 0.458359
## 3      0.02757      0.03858  0.03590     0.08270 0.01309 20.651      1 0.429895
## 4      0.02924      0.04005  0.03772     0.08771 0.01353 20.644      1 0.434969
## 5      0.03490      0.04825  0.04465     0.10470 0.01767 19.649      1 0.417356
## 6      0.02328      0.03526  0.03243     0.06985 0.01222 21.378      1 0.415564
##        DFA   spread1  spread2       D2      PPE
## 1 0.815285 -4.813031 0.266482 2.301442 0.284654
## 2 0.819521 -4.075192 0.335590 2.486855 0.368674
## 3 0.825288 -4.443179 0.311173 2.342259 0.332634
## 4 0.819235 -4.117501 0.334147 2.405554 0.368975
## 5 0.823484 -3.747787 0.234513 2.332180 0.410335
## 6 0.825069 -4.242867 0.299111 2.187560 0.357775</code></pre>
<pre class="r"><code>dim(data)</code></pre>
<pre><code>## [1] 195  24</code></pre>
<pre class="r"><code>na = colSums(is.na(data))</code></pre>
<p>no missing values.</p>
<p>So “status” is our variable of interest. We would like to predict the class of the ‘status’ of any individuals. It’s a classification problem. We are going to use various classification algorithm for this problem. # Feature scaling</p>
<pre class="r"><code>data[,-  c(1,18)] &lt;- scale(data[,-c(1,18)])</code></pre>
<p>#define the columns that contain your abundance data. Change the number after the “:” to subset your data</p>
<pre class="r"><code>com = data[,2:23]</code></pre>
<p>Now create a correlation matrix with your community composition data using the command ‘cor’</p>
<pre class="r"><code>cc = cor(com, method = &quot;spearman&quot;)</code></pre>
<p>Now you have a correlation matrix that contains correlation coefficients for every pairwise combination of variables in our data and Spearman captures all types of positive or negative relationships Spearman correlation: is a non-parametric measure of rank correlation and assesses how well a relationship between two variables can be described using a monotonic function. The easiest way to visualize this correlation matrix is using the function “ggcorrplot” from the package ggcorrplot</p>
<pre class="r"><code>library(ggcorrplot)</code></pre>
<pre><code>## Warning: package &#39;ggcorrplot&#39; was built under R version 4.0.2</code></pre>
<pre><code>## Loading required package: ggplot2</code></pre>
<pre class="r"><code>ggcorrplot(cc,hc.order=&quot;TRUE&quot;)</code></pre>
<p><img src="Parkinsons-notebook_files/figure-html/unnamed-chunk-6-1.png" width="1152" /> It is clear that correlated features means that they bring the same information, so it is logical to remove one of them. When we have highly correlated features, the variance will be large.</p>
<p>Removing the highly correlated variables</p>
<pre class="r"><code>  data &lt;- subset(data, select = -c(1,5,6,8,10,11,12,14))</code></pre>
<p>Now we have removed the highly correlated variables from the dataset.</p>
<p>now we age going to split our data into training and test data</p>
<pre class="r"><code>library(caTools)</code></pre>
<pre><code>## Warning: package &#39;caTools&#39; was built under R version 4.0.2</code></pre>
<pre class="r"><code>set.seed(10)
split=sample.split(data$status,SplitRatio = .80)
train=subset(data,split==T)
test=subset(data,split==F)</code></pre>
<p>Model fitting</p>
<pre class="r"><code>library(caret)</code></pre>
<pre><code>## Warning: package &#39;caret&#39; was built under R version 4.0.2</code></pre>
<pre><code>## Loading required package: lattice</code></pre>
<pre class="r"><code>model.lg= glm(data=train,status~.,family = &quot;binomial&quot;)
summary(model.lg)</code></pre>
<pre><code>## 
## Call:
## glm(formula = status ~ ., family = &quot;binomial&quot;, data = train)
## 
## Deviance Residuals: 
##      Min        1Q    Median        3Q       Max  
## -2.39763   0.00029   0.08014   0.42576   1.89730  
## 
## Coefficients:
##              Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)    3.1734     0.6793   4.671 2.99e-06 ***
## MDVP.Fo.Hz.    0.5564     0.7289   0.763    0.445    
## MDVP.Fhi.Hz.  -0.3203     0.4997  -0.641    0.522    
## MDVP.Flo.Hz.  -0.4648     0.4410  -1.054    0.292    
## MDVP.RAP      65.4977   352.7336   0.186    0.853    
## Jitter.DDP   -63.9250   352.7201  -0.181    0.856    
## Shimmer.APQ5   1.9794     2.4656   0.803    0.422    
## Shimmer.DDA   -0.6004     1.9398  -0.310    0.757    
## NHR           -1.8966     1.6291  -1.164    0.244    
## HNR            0.6631     0.8554   0.775    0.438    
## RPDE          -0.3763     0.4799  -0.784    0.433    
## DFA            0.2777     0.5017   0.553    0.580    
## spread1        1.9252     2.8968   0.665    0.506    
## spread2        0.6011     0.4736   1.269    0.204    
## D2             0.9467     0.6058   1.563    0.118    
## PPE            0.6101     2.9467   0.207    0.836    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 173.217  on 155  degrees of freedom
## Residual deviance:  83.741  on 140  degrees of freedom
## AIC: 115.74
## 
## Number of Fisher Scoring iterations: 8</code></pre>
<pre class="r"><code>step(model.lg,direction=&quot;backward&quot;)</code></pre>
<pre><code>## Start:  AIC=115.74
## status ~ MDVP.Fo.Hz. + MDVP.Fhi.Hz. + MDVP.Flo.Hz. + MDVP.RAP + 
##     Jitter.DDP + Shimmer.APQ5 + Shimmer.DDA + NHR + HNR + RPDE + 
##     DFA + spread1 + spread2 + D2 + PPE
## 
##                Df Deviance    AIC
## - Jitter.DDP    1   83.774 113.77
## - MDVP.RAP      1   83.776 113.78
## - PPE           1   83.783 113.78
## - Shimmer.DDA   1   83.834 113.83
## - DFA           1   84.051 114.05
## - MDVP.Fhi.Hz.  1   84.183 114.18
## - spread1       1   84.285 114.28
## - MDVP.Fo.Hz.   1   84.342 114.34
## - RPDE          1   84.364 114.36
## - HNR           1   84.366 114.37
## - Shimmer.APQ5  1   84.399 114.40
## - MDVP.Flo.Hz.  1   84.848 114.85
## - NHR           1   85.126 115.13
## - spread2       1   85.377 115.38
## &lt;none&gt;              83.741 115.74
## - D2            1   86.503 116.50
## 
## Step:  AIC=113.77
## status ~ MDVP.Fo.Hz. + MDVP.Fhi.Hz. + MDVP.Flo.Hz. + MDVP.RAP + 
##     Shimmer.APQ5 + Shimmer.DDA + NHR + HNR + RPDE + DFA + spread1 + 
##     spread2 + D2 + PPE
## 
##                Df Deviance    AIC
## - PPE           1   83.815 111.81
## - Shimmer.DDA   1   83.858 111.86
## - DFA           1   84.104 112.10
## - MDVP.Fhi.Hz.  1   84.194 112.19
## - spread1       1   84.324 112.32
## - RPDE          1   84.364 112.36
## - MDVP.Fo.Hz.   1   84.393 112.39
## - Shimmer.APQ5  1   84.422 112.42
## - HNR           1   84.453 112.45
## - MDVP.RAP      1   84.701 112.70
## - MDVP.Flo.Hz.  1   84.854 112.85
## - NHR           1   85.136 113.14
## - spread2       1   85.443 113.44
## &lt;none&gt;              83.774 113.77
## - D2            1   86.514 114.51
## 
## Step:  AIC=111.81
## status ~ MDVP.Fo.Hz. + MDVP.Fhi.Hz. + MDVP.Flo.Hz. + MDVP.RAP + 
##     Shimmer.APQ5 + Shimmer.DDA + NHR + HNR + RPDE + DFA + spread1 + 
##     spread2 + D2
## 
##                Df Deviance    AIC
## - Shimmer.DDA   1   83.944 109.94
## - DFA           1   84.149 110.15
## - MDVP.Fhi.Hz.  1   84.277 110.28
## - RPDE          1   84.383 110.38
## - MDVP.Fo.Hz.   1   84.482 110.48
## - HNR           1   84.520 110.52
## - Shimmer.APQ5  1   84.587 110.59
## - MDVP.RAP      1   84.793 110.79
## - MDVP.Flo.Hz.  1   84.868 110.87
## - NHR           1   85.139 111.14
## - spread2       1   85.455 111.45
## &lt;none&gt;              83.815 111.81
## - D2            1   86.514 112.51
## - spread1       1   91.343 117.34
## 
## Step:  AIC=109.94
## status ~ MDVP.Fo.Hz. + MDVP.Fhi.Hz. + MDVP.Flo.Hz. + MDVP.RAP + 
##     Shimmer.APQ5 + NHR + HNR + RPDE + DFA + spread1 + spread2 + 
##     D2
## 
##                Df Deviance    AIC
## - DFA           1   84.322 108.32
## - MDVP.Fhi.Hz.  1   84.348 108.35
## - RPDE          1   84.527 108.53
## - HNR           1   84.653 108.65
## - MDVP.Fo.Hz.   1   84.685 108.69
## - MDVP.RAP      1   84.798 108.80
## - MDVP.Flo.Hz.  1   85.002 109.00
## - NHR           1   85.166 109.17
## - spread2       1   85.460 109.46
## &lt;none&gt;              83.944 109.94
## - Shimmer.APQ5  1   86.598 110.60
## - D2            1   86.659 110.66
## - spread1       1   92.972 116.97
## 
## Step:  AIC=108.32
## status ~ MDVP.Fo.Hz. + MDVP.Fhi.Hz. + MDVP.Flo.Hz. + MDVP.RAP + 
##     Shimmer.APQ5 + NHR + HNR + RPDE + spread1 + spread2 + D2
## 
##                Df Deviance    AIC
## - MDVP.Fo.Hz.   1   84.754 106.75
## - MDVP.Fhi.Hz.  1   84.903 106.90
## - HNR           1   84.979 106.98
## - RPDE          1   85.278 107.28
## - MDVP.Flo.Hz.  1   85.281 107.28
## - MDVP.RAP      1   86.089 108.09
## &lt;none&gt;              84.322 108.32
## - spread2       1   86.396 108.40
## - NHR           1   86.648 108.65
## - D2            1   86.946 108.95
## - Shimmer.APQ5  1   87.184 109.18
## - spread1       1   93.010 115.01
## 
## Step:  AIC=106.75
## status ~ MDVP.Fhi.Hz. + MDVP.Flo.Hz. + MDVP.RAP + Shimmer.APQ5 + 
##     NHR + HNR + RPDE + spread1 + spread2 + D2
## 
##                Df Deviance    AIC
## - MDVP.Fhi.Hz.  1   85.052 105.05
## - HNR           1   85.107 105.11
## - MDVP.Flo.Hz.  1   85.301 105.30
## - RPDE          1   85.981 105.98
## - spread2       1   86.568 106.57
## &lt;none&gt;              84.754 106.75
## - MDVP.RAP      1   86.900 106.90
## - Shimmer.APQ5  1   87.436 107.44
## - NHR           1   87.541 107.54
## - D2            1   87.908 107.91
## - spread1       1   93.711 113.71
## 
## Step:  AIC=105.05
## status ~ MDVP.Flo.Hz. + MDVP.RAP + Shimmer.APQ5 + NHR + HNR + 
##     RPDE + spread1 + spread2 + D2
## 
##                Df Deviance    AIC
## - HNR           1   85.485 103.48
## - MDVP.Flo.Hz.  1   85.630 103.63
## - RPDE          1   86.449 104.45
## &lt;none&gt;              85.052 105.05
## - MDVP.RAP      1   87.322 105.32
## - spread2       1   87.342 105.34
## - D2            1   87.908 105.91
## - NHR           1   88.179 106.18
## - Shimmer.APQ5  1   88.207 106.21
## - spread1       1   94.127 112.13
## 
## Step:  AIC=103.49
## status ~ MDVP.Flo.Hz. + MDVP.RAP + Shimmer.APQ5 + NHR + RPDE + 
##     spread1 + spread2 + D2
## 
##                Df Deviance    AIC
## - MDVP.Flo.Hz.  1   86.300 102.30
## &lt;none&gt;              85.485 103.48
## - MDVP.RAP      1   87.485 103.48
## - D2            1   88.011 104.01
## - Shimmer.APQ5  1   88.428 104.43
## - spread2       1   88.447 104.45
## - RPDE          1   88.704 104.70
## - NHR           1   89.732 105.73
## - spread1       1   94.476 110.48
## 
## Step:  AIC=102.3
## status ~ MDVP.RAP + Shimmer.APQ5 + NHR + RPDE + spread1 + spread2 + 
##     D2
## 
##                Df Deviance    AIC
## - MDVP.RAP      1   88.049 102.05
## &lt;none&gt;              86.300 102.30
## - D2            1   88.412 102.41
## - Shimmer.APQ5  1   89.264 103.26
## - spread2       1   89.368 103.37
## - RPDE          1   89.412 103.41
## - NHR           1   89.799 103.80
## - spread1       1  102.968 116.97
## 
## Step:  AIC=102.05
## status ~ Shimmer.APQ5 + NHR + RPDE + spread1 + spread2 + D2
## 
##                Df Deviance    AIC
## - D2            1   89.738 101.74
## - NHR           1   89.817 101.82
## &lt;none&gt;              88.049 102.05
## - spread2       1   90.204 102.20
## - RPDE          1   91.304 103.30
## - Shimmer.APQ5  1   92.361 104.36
## - spread1       1  109.896 121.90
## 
## Step:  AIC=101.74
## status ~ Shimmer.APQ5 + NHR + RPDE + spread1 + spread2
## 
##                Df Deviance    AIC
## - NHR           1   90.904 100.90
## &lt;none&gt;              89.738 101.74
## - spread2       1   93.697 103.70
## - Shimmer.APQ5  1   96.209 106.21
## - RPDE          1   96.382 106.38
## - spread1       1  113.552 123.55
## 
## Step:  AIC=100.9
## status ~ Shimmer.APQ5 + RPDE + spread1 + spread2
## 
##                Df Deviance    AIC
## &lt;none&gt;              90.904 100.90
## - spread2       1   94.572 102.57
## - Shimmer.APQ5  1   96.217 104.22
## - RPDE          1   98.104 106.10
## - spread1       1  115.416 123.42</code></pre>
<pre><code>## 
## Call:  glm(formula = status ~ Shimmer.APQ5 + RPDE + spread1 + spread2, 
##     family = &quot;binomial&quot;, data = train)
## 
## Coefficients:
##  (Intercept)  Shimmer.APQ5          RPDE       spread1       spread2  
##       2.9792        1.3524       -0.9188        2.8468        0.6879  
## 
## Degrees of Freedom: 155 Total (i.e. Null);  151 Residual
## Null Deviance:       173.2 
## Residual Deviance: 90.9  AIC: 100.9</code></pre>
<p>The Akaike information criterion (AIC) is an estimator of out-of-sample prediction error and thereby relative quality of statistical models for a given set of data.Lower AIC values indicate a better-fit model</p>
<p>We will select the model with lowest AIC that is status ~ Shimmer.APQ5 + RPDE + spread1 + spread2</p>
<pre class="r"><code>final.model=  glm(formula = status ~ Shimmer.APQ5 + RPDE + spread1 + spread2, 
    family = &quot;binomial&quot;, data = train)

summary(final.model)</code></pre>
<pre><code>## 
## Call:
## glm(formula = status ~ Shimmer.APQ5 + RPDE + spread1 + spread2, 
##     family = &quot;binomial&quot;, data = train)
## 
## Deviance Residuals: 
##      Min        1Q    Median        3Q       Max  
## -2.19323   0.00086   0.14142   0.47529   1.71789  
## 
## Coefficients:
##              Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)    2.9792     0.5342   5.577 2.44e-08 ***
## Shimmer.APQ5   1.3524     0.7138   1.895   0.0581 .  
## RPDE          -0.9188     0.3608  -2.547   0.0109 *  
## spread1        2.8468     0.6984   4.076 4.58e-05 ***
## spread2        0.6879     0.3706   1.856   0.0635 .  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 173.217  on 155  degrees of freedom
## Residual deviance:  90.904  on 151  degrees of freedom
## AIC: 100.9
## 
## Number of Fisher Scoring iterations: 7</code></pre>
<p>We will check our model’s accuracy now. First we will use our training data.</p>
<p>Fitting the model</p>
<pre class="r"><code>train$pred&lt;-fitted(final.model)</code></pre>
<p>Predicting the train dataset</p>
<pre class="r"><code>library(ROCR)</code></pre>
<pre><code>## Warning: package &#39;ROCR&#39; was built under R version 4.0.2</code></pre>
<pre class="r"><code>pred &lt;-prediction(train$pred,train$status)</code></pre>
<p>Create Performance Objects and plotting graph</p>
<pre class="r"><code>perf&lt;-performance(pred,&quot;tpr&quot;,&quot;fpr&quot;)
plot(perf,colorize = T,print.cutoffs.at = seq(0.1,by = 0.1))</code></pre>
<p><img src="Parkinsons-notebook_files/figure-html/unnamed-chunk-13-1.png" width="1152" /> With the use of ROC curve we can observe that 0.8 is having better sensitivity and specificity.There we select 0.8 as our cutoff to distinguish.</p>
<pre class="r"><code>pre &lt;- as.numeric(predict(final.model,type=&quot;response&quot;)&gt;0.8)</code></pre>
<p>creating the confusion matrix</p>
<pre class="r"><code>confusionMatrix(table(pre,train$status))</code></pre>
<pre><code>## Confusion Matrix and Statistics
## 
##    
## pre  0  1
##   0 32 24
##   1  6 94
##                                          
##                Accuracy : 0.8077         
##                  95% CI : (0.737, 0.8663)
##     No Information Rate : 0.7564         
##     P-Value [Acc &gt; NIR] : 0.078318       
##                                          
##                   Kappa : 0.5503         
##                                          
##  Mcnemar&#39;s Test P-Value : 0.001911       
##                                          
##             Sensitivity : 0.8421         
##             Specificity : 0.7966         
##          Pos Pred Value : 0.5714         
##          Neg Pred Value : 0.9400         
##              Prevalence : 0.2436         
##          Detection Rate : 0.2051         
##    Detection Prevalence : 0.3590         
##       Balanced Accuracy : 0.8194         
##                                          
##        &#39;Positive&#39; Class : 0              
## </code></pre>
<p>Accuracy of training data From confusion matrix of training data, we come to know that our model is 81.94% accurate.</p>
<p>Now validating the model on testing data</p>
<pre class="r"><code>pre  &lt;- as.numeric(predict(final.model,newdata=test,type=&quot;response&quot;)&gt;0.8)</code></pre>
<p># type = “response” is used to get the outcome in the form of probability of having parkinson’s disease. As we know that, for training data the cutoff has been 0.8.Similarly the testing data will also have the same threshold or cutoff.</p>
<p>making the confusion matrix</p>
<pre class="r"><code>confusionMatrix(table(pre,test$status))</code></pre>
<pre><code>## Confusion Matrix and Statistics
## 
##    
## pre  0  1
##   0  8  5
##   1  2 24
##                                           
##                Accuracy : 0.8205          
##                  95% CI : (0.6647, 0.9246)
##     No Information Rate : 0.7436          
##     P-Value [Acc &gt; NIR] : 0.1808          
##                                           
##                   Kappa : 0.5714          
##                                           
##  Mcnemar&#39;s Test P-Value : 0.4497          
##                                           
##             Sensitivity : 0.8000          
##             Specificity : 0.8276          
##          Pos Pred Value : 0.6154          
##          Neg Pred Value : 0.9231          
##              Prevalence : 0.2564          
##          Detection Rate : 0.2051          
##    Detection Prevalence : 0.3333          
##       Balanced Accuracy : 0.8138          
##                                           
##        &#39;Positive&#39; Class : 0               
## </code></pre>
<p>Balanced Accuracy of Testing data is 81.38%</p>
<p>To check how much of our predicted values lie inside the curve</p>
<pre class="r"><code>auc&lt;-performance(pred,&quot;auc&quot;)
auc@y.values</code></pre>
<pre><code>## [[1]]
## [1] 0.9203836</code></pre>
<p>We can conclude that we are getting an accuracy of 81.38 %. Also our misclassifcation rate is 18.62%</p>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
